[plugins]
blossom = "net.kyori.blossom:2.2.0"

[libraries]
luckperms = "net.luckperms:api:5.5"
velocity = "com.velocitypowered:velocity-api:3.4.0-SNAPSHOT"
packetevents = "com.github.retrooper:packetevents-velocity:2.11.1"
